version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "âœ… Installing Docker in CodeBuild"
      - nohup dockerd &

  build:
    commands:
      - echo "ðŸ³ Building Docker image..."
      - docker build -t voicebot-app .

  post_build:
    commands:
      - echo "ðŸš€ Deploying to EC2"
      - echo "$EC2_PRIVATE_KEY" > ec2-key.pem
      - chmod 400 ec2-key.pem
      - scp -i ec2-key.pem -o StrictHostKeyChecking=no -r . ubuntu@$EC2_HOST:/home/ubuntu/voice-chatbot/
      - ssh -i ec2-key.pem -o StrictHostKeyChecking=no ubuntu@$EC2_HOST "
          cd /home/ubuntu/voice-chatbot &&
          docker stop voicebot-app || true &&
          docker rm voicebot-app || true &&
          docker build -t voicebot-app . &&
          docker run -d -p 8000:8000 --name voicebot-app voicebot-app
        "

env:
  secrets-manager:
    EC2_PRIVATE_KEY: "EC2_PRIVATE_KEY"  # Store your private SSH key securely
  variables:
    EC2_HOST: "52.87.247.29"
